version: "3.9"
services:
  db:
    build: ./db
    container_name: payments-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_pass

  transfer-service3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transfer-service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paymentsdb
      SPRING_DATASOURCE_USERNAME: payments_user
      SPRING_DATASOURCE_PASSWORD: payments_pass
      SERVER_PORT: 8080
      LEDGER_SERVICE_URL: http://ledger-service:8081
    ports:
      - 8080:8080
